CREATE TABLE [HSPL].[ADMISSIONS](
	[ADMISSION_NO] [int] IDENTITY(1,1) NOT NULL,
	[PATIENT_ID] [int] NULL,
	[DOCTOR_ID] [int] NULL,
	[SPECIALISATION_ID] [int] NULL,
	[HOSPITAL_ID] [int] NULL,
	[ADMISSION_DATE] [date] NULL,
	[ISEMERGENCY] [bit] NULL,
	[ISOP] [bit] NULL,
	[PERSON_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ADMISSION_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [HSPL].[ADMISSIONS] ADD  DEFAULT ((0)) FOR [ISEMERGENCY]
GO

ALTER TABLE [HSPL].[ADMISSIONS] ADD  DEFAULT ((0)) FOR [ISOP]
GO

ALTER TABLE [HSPL].[ADMISSIONS]  WITH CHECK ADD FOREIGN KEY([DOCTOR_ID])
REFERENCES [HSPL].[DOCTORS] ([DOCTOR_ID])
GO

ALTER TABLE [HSPL].[ADMISSIONS]  WITH CHECK ADD FOREIGN KEY([HOSPITAL_ID])
REFERENCES [HSPL].[HOSPITALS] ([HOSPITAL_ID])
GO

ALTER TABLE [HSPL].[ADMISSIONS]  WITH CHECK ADD FOREIGN KEY([PATIENT_ID])
REFERENCES [HSPL].[PATIENTS] ([PATIENT_ID])
GO

ALTER TABLE [HSPL].[ADMISSIONS]  WITH CHECK ADD FOREIGN KEY([PERSON_ID])
REFERENCES [HSPL].[RECEPTION] ([PERSON_ID])
GO

ALTER TABLE [HSPL].[ADMISSIONS]  WITH CHECK ADD FOREIGN KEY([SPECIALISATION_ID])
REFERENCES [HSPL].[SPECIALISATIONS] ([SPECIALISATION_ID])
GO