CREATE TABLE [HSPL].[DOCTORS](
	[DOCTOR_ID] [int] IDENTITY(1,1) NOT NULL,
	[DOCTOR_NAME] [nvarchar](275) NULL,
	[AGE] [int] NULL,
	[GENDER] [nvarchar](15) NULL,
	[EMAIL] [nvarchar](30) NULL,
	[PHONE_NUMBER] [bigint] NULL,
	[SPECIALISATION_ID] [int] NULL,
	[HOSPITAL_ID] [int] NULL,
	[EXPERIENCE] [int] NULL,
	[AVAILABILITY_STATUS] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DOCTOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [HSPL].[DOCTORS]  WITH CHECK ADD FOREIGN KEY([HOSPITAL_ID])
REFERENCES [HSPL].[HOSPITALS] ([HOSPITAL_ID])
GO

ALTER TABLE [HSPL].[DOCTORS]  WITH CHECK ADD FOREIGN KEY([SPECIALISATION_ID])
REFERENCES [HSPL].[SPECIALISATIONS] ([SPECIALISATION_ID])
GO