CREATE TABLE [HSPL].[HOSPITALS](
	[HOSPITAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[HOSPITAL_NAME] [nvarchar](275) NULL,
	[EMAIL] [nvarchar](30) NULL,
	[PHONE_NUMBER] [bigint] NULL,
	[LOCATION] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[HOSPITAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO