CREATE TABLE [SKHSPL].[ADMIN](
	[ADMIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[ADMIN_NAME] [nvarchar](275) NULL,
PRIMARY KEY CLUSTERED 
(
	[ADMIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO